r"""
Track views/downloads for your published Zenodo records and log them over time.

Every run appends one timestamped row per record to a local CSV, then prints an
ASCII table sorted by downloads with a DELTA column showing what changed since
the previous run, plus a downloads-per-day rate so a record published in 2019
can be compared fairly against one published last week.

READ-ONLY. This script issues GET requests only -- there is no code path here
that can create, modify, publish or delete anything on Zenodo.

    $env:ZENODO_TOKEN="..."                  # PowerShell
    python zenodo_stats.py                   # table + append to history CSV
    python zenodo_stats.py --json            # raw data to stdout instead
    python zenodo_stats.py --html stats.html # also write an HTML dashboard
    python zenodo_stats.py --csv D:\logs\zenodo.csv
    python zenodo_stats.py --no-history      # show only, do not touch the CSV
    python zenodo_stats.py --record 6000557  # public record ids, no token needed
    python zenodo_stats.py --html x.html --force   # overwrite a foreign x.html

Set ZENODO_BASE to https://sandbox.zenodo.org to point at the sandbox.

The only files written are the history CSV (appended to, and only if it carries
this tool's own header) and the optional --html dashboard.

Requests are spaced out to stay inside Zenodo's published budget (60/min as a
guest, 100/min authenticated) and the server's own x-ratelimit headers are
honoured on top of that, so a large collection is fetched slowly rather than
being hammered into a 429.
"""
import os
import sys
import csv
import json
import time
import html
import argparse
import datetime
import unicodedata
import email.utils

import requests

BASE = os.environ.get("ZENODO_BASE", "https://zenodo.org").rstrip("/")
TOKEN = os.environ.get("ZENODO_TOKEN")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CSV = os.path.join(SCRIPT_DIR, "zenodo_stats_history.csv")

CSV_COLUMNS = ["timestamp", "record_id", "title", "publication_date",
               "views", "downloads", "unique_views", "unique_downloads"]
STAT_KEYS = ["views", "downloads", "unique_views", "unique_downloads"]

PAGE_SIZE = 100              # the max Zenodo allows; guests are capped at 25
MAX_PAGES = 200              # hard stop so a misbehaving pager cannot loop forever
MIN_GAP_GUEST = 1.05         # documented guest budget is 60 requests/minute
MIN_GAP_AUTH = 0.65          # documented authenticated budget is 100 requests/minute
MAX_BACKOFF = 120.0          # never sleep longer than this on a 429
TITLE_MAX = 44

JSON_MODE = False            # when true, chatter goes to stderr

HTML_MARKER = "<!-- generated by zenodo_stats.py -->"

# Punctuation that has no ASCII equivalent but a decent ASCII stand-in.
TRANSLIT = {
    0x2018: "'", 0x2019: "'", 0x201a: "'", 0x201b: "'",
    0x201c: '"', 0x201d: '"', 0x201e: '"', 0x2033: '"',
    0x2010: "-", 0x2011: "-", 0x2012: "-", 0x2013: "-", 0x2014: "-", 0x2015: "-",
    0x2026: "...", 0x00a0: " ", 0x202f: " ", 0x2009: " ", 0x00ad: "",
    0x2022: "*", 0x00b7: "*", 0x00d7: "x", 0x00f7: "/",
    0x2190: "<-", 0x2192: "->", 0x2264: "<=", 0x2265: ">=", 0x2260: "!=",
    0x00b0: "deg", 0x20ac: "EUR", 0x00a3: "GBP", 0x2122: "(TM)", 0x00ae: "(R)",
    0x00a9: "(C)", 0x2032: "'",
    # Latin letters that carry their stroke inside the glyph, so NFKD leaves
    # them whole and they would otherwise degrade to '?'.
    0x0141: "L", 0x0142: "l", 0x00d8: "O", 0x00f8: "o", 0x0110: "D", 0x0111: "d",
    0x00c6: "AE", 0x00e6: "ae", 0x0152: "OE", 0x0153: "oe", 0x00df: "ss",
    0x00de: "Th", 0x00fe: "th", 0x00d0: "D", 0x00f0: "d", 0x0131: "i",
    0x0130: "I", 0x00d1: "N", 0x00f1: "n", 0x0126: "H", 0x0127: "h",
}


def ascii_safe(text):
    """Fold arbitrary Unicode down to plain ASCII for console output.

    Record titles and API error bodies come back from the server and routinely
    contain accents, typographic dashes and non-Latin scripts. A Windows
    console is cp1252 and raises UnicodeEncodeError on anything it cannot map,
    which would kill the run with a traceback instead of printing the report,
    so nothing reaches the terminal without passing through here. The CSV and
    the HTML dashboard are UTF-8 and keep the original text intact.
    """
    s = str(text).translate(TRANSLIT)
    # Decompose so accented letters keep their base form (e -> e, a -> a),
    # then drop the combining marks that are left over.
    s = "".join(c for c in unicodedata.normalize("NFKD", s)
                if not unicodedata.combining(c))
    return s.encode("ascii", "replace").decode("ascii")


def write_line(stream, msg):
    stream.write(ascii_safe(msg) + "\n")
    stream.flush()


def note(msg=""):
    """Progress text. Kept off stdout in --json mode so the dump stays clean."""
    write_line(sys.stderr if JSON_MODE else sys.stdout, msg)


def show(msg=""):
    """Report output. Always stdout, always ASCII."""
    write_line(sys.stdout, msg)


def as_int(value):
    """Zenodo stats are ints today; tolerate floats, numeric strings and nulls."""
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return 0


def mask(token):
    if not token:
        return "(none)"
    if len(token) <= 10:
        return "*" * len(token)
    return f"{token[:6]}...{token[-4:]} ({len(token)} chars)"


# --------------------------------------------------------------- http (GET only)

_last_request = [0.0]        # monotonic clock reading of the previous GET


def throttle(auth):
    """Space requests out so a long run stays inside the published budget.

    Spacing is measured from the previous request rather than slept blindly
    after it, so time already spent waiting on the network counts towards the
    gap and a slow connection is not penalised twice.
    """
    gap = MIN_GAP_AUTH if auth else MIN_GAP_GUEST
    wait = gap - (time.monotonic() - _last_request[0])
    if wait > 0:
        time.sleep(wait)
    _last_request[0] = time.monotonic()


def observe_limits(r):
    """Pause when the server says the current rate window is nearly spent."""
    try:
        remaining = int(r.headers.get("x-ratelimit-remaining", ""))
        reset = int(r.headers.get("x-ratelimit-reset", ""))
    except (TypeError, ValueError):
        return
    if remaining > 3:
        return
    wait = min(max(reset - time.time(), 0.0) + 1.0, MAX_BACKOFF)
    if wait > 0:
        note(f"  rate budget nearly spent ({remaining} left), pausing {wait:.0f}s ...")
        time.sleep(wait)


def retry_delay(r, attempt):
    """Seconds to wait after a 429.

    Retry-After is legally either a count of seconds or an HTTP date, and a
    bare int() on the date form would raise straight through the caller.
    """
    raw = (r.headers.get("Retry-After") or "").strip()
    wait = None
    if raw:
        try:
            wait = float(int(raw))
        except ValueError:
            try:
                when = email.utils.parsedate_to_datetime(raw)
                if when is not None:
                    if when.tzinfo is None:
                        when = when.replace(tzinfo=datetime.timezone.utc)
                    now = datetime.datetime.now(datetime.timezone.utc)
                    wait = (when - now).total_seconds()
            except (TypeError, ValueError, OverflowError):
                wait = None
    if wait is None or wait <= 0:
        wait = 5.0 * attempt
    return min(wait, MAX_BACKOFF)


def get(session, url, params=None, auth=False, tries=3):
    """GET with 429 backoff. Returns the decoded body, or None after reporting."""
    headers = {"Authorization": f"Bearer {TOKEN}"} if auth and TOKEN else {}
    for attempt in range(1, tries + 1):
        throttle(auth)
        try:
            r = session.get(url, params=params, headers=headers, timeout=60)
        except requests.RequestException as exc:
            note(f"  network error on {url}: {exc.__class__.__name__}")
            return None
        if r.status_code == 429:
            wait = retry_delay(r, attempt)
            note(f"  rate limited (429), waiting {wait:.0f}s ...")
            time.sleep(wait)
            continue
        observe_limits(r)
        if r.status_code == 200:
            try:
                return r.json()
            except ValueError:
                note(f"  {url} returned non-JSON: {r.text[:200]}")
                return None
        note(f"  HTTP {r.status_code} on {url}")
        body = r.text.strip().replace("\n", " ")
        if body:
            note(f"    {body[:300]}")
        if auth and r.status_code in (400, 401, 403):
            # Zenodo does not reject a bad Bearer token outright -- it drops
            # you to guest access, so a stale token shows up as whatever guests
            # are not allowed to do (e.g. "page size cannot be greater than
            # 25") rather than as a straightforward 401.
            note("    the token was not accepted, so this ran as a guest.")
            note("    check that ZENODO_TOKEN is current, has the "
                 "deposit:actions/deposit:write scopes, and belongs to "
                 f"{BASE} -- sandbox and production tokens are not "
                 "interchangeable.")
        return None
    note(f"  gave up on {url} after {tries} attempts")
    return None


def fetch_depositions(session):
    """GET /api/deposit/depositions, paginated until a short page comes back."""
    out, page = [], 1
    while page <= MAX_PAGES:
        batch = get(session, f"{BASE}/api/deposit/depositions",
                    params={"size": PAGE_SIZE, "page": page}, auth=True)
        if batch is None:
            return None
        if not isinstance(batch, list):
            note(f"  unexpected depositions payload: {str(batch)[:200]}")
            return None
        out.extend(batch)
        note(f"  page {page}: {len(batch)} deposition(s)")
        if len(batch) < PAGE_SIZE:
            return out
        page += 1
    note(f"  stopping at the {MAX_PAGES}-page ceiling ({len(out)} so far)")
    return out


def fetch_record(session, record_id, auth=False):
    """GET /api/records/:id -- public endpoint; a token only raises the rate cap."""
    return get(session, f"{BASE}/api/records/{record_id}", auth=auth)


# ------------------------------------------------------------------------ dates

def days_since(publication_date):
    """Whole days from an ISO 'YYYY-MM-DD' to today. None if unparseable."""
    if not publication_date:
        return None
    try:
        parts = [int(x) for x in str(publication_date)[:10].split("-")]
        pub = datetime.date(parts[0], parts[1], parts[2])
    except (ValueError, TypeError, IndexError):
        return None
    return (datetime.date.today() - pub).days


def per_day(downloads, days):
    """Downloads per day. Same-day (or future-dated) publications count as 1 day."""
    if days is None:
        return None
    return downloads / float(max(days, 1))


# ------------------------------------------------------------------------- csv

def load_history(path):
    if not os.path.isfile(path):
        return []
    rows = []
    try:
        # utf-8-sig: the file may have been opened and re-saved by Excel, which
        # adds a BOM that would otherwise become part of the first column name.
        with open(path, "r", encoding="utf-8-sig", newline="",
                  errors="replace") as fh:
            for raw in csv.DictReader(fh):
                if not raw.get("timestamp") or not raw.get("record_id"):
                    continue
                row = dict(raw)
                for k in STAT_KEYS:
                    row[k] = as_int(row.get(k))
                rows.append(row)
    except (OSError, csv.Error, UnicodeError) as exc:
        note(f"  could not read history {path}: {exc}")
        return []
    return rows


def history_is_compatible(path):
    """True unless PATH exists and is some other file we would corrupt.

    The history is opened in append mode, so pointing --csv at an unrelated
    file would quietly staple stat rows onto the end of it. Only append to a
    file that carries our own header.
    """
    if not os.path.isfile(path):
        return True
    try:
        with open(path, "r", encoding="utf-8-sig", newline="",
                  errors="replace") as fh:
            header = next(csv.reader(fh), None)
    except (OSError, csv.Error, UnicodeError):
        return False         # unreadable: cannot prove it is ours, so leave it
    if header is None:
        return True          # empty file, safe to claim
    return [h.strip() for h in header] == CSV_COLUMNS


def append_history(path, rows):
    new_file = not os.path.isfile(path)
    parent = os.path.dirname(os.path.abspath(path))
    if parent and not os.path.isdir(parent):
        note(f"  history directory does not exist: {parent}")
        return False
    if not history_is_compatible(path):
        note(f"  refusing to append: {path} exists and does not carry this "
             "tool's CSV header.")
        note("  pass a different --csv path, or move that file aside.")
        return False
    try:
        with open(path, "a", encoding="utf-8", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=CSV_COLUMNS)
            if new_file:
                w.writeheader()
            for r in rows:
                w.writerow({k: r[k] for k in CSV_COLUMNS})
    except OSError as exc:
        note(f"  could not write history {path}: {exc}")
        return False
    return True


def previous_snapshot(history):
    """The most recent complete run already in the CSV: {record_id: row}."""
    if not history:
        return {}, None
    prev_ts = max(r["timestamp"] for r in history)
    return {r["record_id"]: r for r in history if r["timestamp"] == prev_ts}, prev_ts


# ----------------------------------------------------------------- ascii output

def print_table(headers, rows, aligns, total_row=None):
    widths = [len(h) for h in headers]
    for r in rows + ([total_row] if total_row else []):
        for i, cell in enumerate(r):
            widths[i] = max(widths[i], len(str(cell)))
    border = "+" + "+".join("-" * (w + 2) for w in widths) + "+"

    def line(r):
        cells = []
        for i, cell in enumerate(r):
            s = str(cell)
            cells.append(" " + (s.ljust(widths[i]) if aligns[i] == "l"
                                else s.rjust(widths[i])) + " ")
        return "|" + "|".join(cells) + "|"

    show(border)
    show(line(headers))
    show(border)
    for r in rows:
        show(line(r))
    if total_row:
        show(border)
        show(line(total_row))
    show(border)


def fmt_delta(cur, prev_row, key):
    if not prev_row:
        return ""
    return f"{cur - prev_row.get(key, 0):+,}"


def clip(text, width=TITLE_MAX):
    # Fold to ASCII *before* measuring: an ellipsis expands to three characters
    # and an accent drops one, so widths computed on the raw string would leave
    # the table columns misaligned.
    text = " ".join(ascii_safe(text or "(untitled)").split())
    return text if len(text) <= width else text[:width - 3] + "..."


def render_table(records, prev, prev_ts):
    headers = ["RECORD", "TITLE", "PUBLISHED", "DAYS", "VIEWS", "DELTA_V",
               "DOWNL", "DELTA_D", "U.VIEWS", "U.DOWNL", "DL/DAY"]
    aligns = ["r", "l", "l", "r", "r", "r", "r", "r", "r", "r", "r"]
    rows = []
    for rec in records:
        p = prev.get(rec["record_id"])
        rate = per_day(rec["downloads"], rec["days"])
        rows.append([
            rec["record_id"],
            clip(rec["title"]),
            rec["publication_date"] or "?",
            # A future publication_date (embargo, scheduled release) would
            # otherwise print as a large negative age.
            "?" if rec["days"] is None else max(rec["days"], 0),
            f"{rec['views']:,}",
            fmt_delta(rec["views"], p, "views"),
            f"{rec['downloads']:,}",
            fmt_delta(rec["downloads"], p, "downloads"),
            f"{rec['unique_views']:,}",
            f"{rec['unique_downloads']:,}",
            "?" if rate is None else f"{rate:.2f}",
        ])

    totals = {k: sum(r[k] for r in records) for k in STAT_KEYS}

    # Sum the per-record deltas rather than differencing the totals: a record
    # with no previous row would otherwise book its whole lifetime count as
    # "change since last run".
    matched = [r for r in records if r["record_id"] in prev]
    delta_totals = {k: sum(r[k] - prev[r["record_id"]].get(k, 0) for r in matched)
                    for k in STAT_KEYS}
    total_row = [
        "TOTAL", f"{len(records)} record(s)", "", "",
        f"{totals['views']:,}",
        f"{delta_totals['views']:+,}" if matched else "",
        f"{totals['downloads']:,}",
        f"{delta_totals['downloads']:+,}" if matched else "",
        f"{totals['unique_views']:,}", f"{totals['unique_downloads']:,}", "",
    ]

    print_table(headers, rows, aligns, total_row)
    show("DL/DAY  = downloads divided by days since publication_date "
         "(same-day counts as 1 day).")
    if not prev_ts:
        show("DELTA_* = blank: this is the first run in this history file.")
    elif len(matched) == len(records):
        show(f"DELTA_* = change since the previous run logged at {prev_ts}.")
    else:
        show(f"DELTA_* = change since the previous run logged at {prev_ts}; "
             f"{len(records) - len(matched)} record(s) are new since then and "
             "are excluded from the TOTAL delta.")


# ------------------------------------------------------------------------- html

def delta_cls(text):
    if not text:
        return "flat"
    if text.startswith("+") and text != "+0":
        return "up"
    if text.startswith("-"):
        return "down"
    return "flat"


def sparkline(values, width=140, height=30):
    if len(values) < 2:
        return '<span class="nodata">not enough history yet</span>'
    lo, hi = min(values), max(values)
    step = (width - 2) / float(len(values) - 1)
    flat = hi == lo
    pts = []
    for i, v in enumerate(values):
        x = 1 + i * step
        # An unchanged series has no shape to show, so draw it down the middle
        # instead of letting it sit on the bottom edge.
        y = height / 2.0 if flat else height - 1 - (v - lo) * (height - 2) / float(hi - lo)
        pts.append("%.1f,%.1f" % (x, y))
    poly = " ".join(pts)
    area = "1,%d %s %.1f,%d" % (height, poly, width - 1, height)
    lx, ly = pts[-1].split(",")
    return (
        '<svg class="spark" viewBox="0 0 %d %d" width="%d" height="%d" '
        'preserveAspectRatio="none" role="img" aria-label="downloads trend">'
        '<polygon points="%s" fill="rgba(37,99,235,0.14)"/>'
        '<polyline points="%s" fill="none" stroke="#2563eb" stroke-width="1.6" '
        'stroke-linejoin="round" stroke-linecap="round"/>'
        '<circle cx="%s" cy="%s" r="2.4" fill="#2563eb"/></svg>'
        % (width, height, width, height, area, poly, lx, ly)
    )


HTML_TEMPLATE = """<!DOCTYPE html>
<!-- generated by zenodo_stats.py -->
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Zenodo metrics</title>
<style>
 :root{color-scheme:light}
 *{box-sizing:border-box}
 body{margin:0;padding:32px 20px;background:#f6f7f9;color:#16181d;
      font:15px/1.5 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif}
 .wrap{max-width:1080px;margin:0 auto}
 h1{margin:0 0 4px;font-size:22px;letter-spacing:-.01em}
 .sub{color:#6b7280;font-size:13px;margin-bottom:22px}
 .cards{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:22px}
 .card{flex:1 1 150px;background:#fff;border:1px solid #e3e6ea;border-radius:10px;
       padding:14px 16px}
 .card b{display:block;font-size:24px;font-weight:600;letter-spacing:-.02em}
 .card span{color:#6b7280;font-size:12px;text-transform:uppercase;letter-spacing:.06em}
 .scroll{overflow-x:auto}
 table{width:100%%;border-collapse:collapse;background:#fff;border:1px solid #e3e6ea;
       border-radius:10px;overflow:hidden}
 th,td{padding:10px 12px;text-align:left;border-bottom:1px solid #eef0f3;
       vertical-align:middle}
 th{background:#f0f2f5;font-size:11px;text-transform:uppercase;letter-spacing:.06em;
    color:#4b5563}
 tr:last-child td{border-bottom:none}
 td.num,th.num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
 td.id{font-family:Consolas,Menlo,monospace;font-size:13px}
 td.id a{color:#2563eb;text-decoration:none}
 td.title{max-width:340px}
 .pub{display:block;color:#6b7280;font-size:12px;margin-top:2px}
 .d{display:block;font-size:12px;margin-top:2px}
 .up{color:#15803d}.down{color:#b91c1c}.flat{color:#9ca3af}
 .spark-cell{width:150px}
 .spark{display:block}
 .nodata{color:#9ca3af;font-size:12px}
 footer{color:#6b7280;font-size:12px;margin-top:18px}
</style></head><body><div class="wrap">
<h1>Zenodo metrics</h1>
<div class="sub">%(base)s &middot; generated %(generated)s &middot; %(runs)s run(s)
 in history &middot; deltas vs %(prev)s</div>
<div class="cards">
 <div class="card"><span>Records</span><b>%(records)s</b></div>
 <div class="card"><span>Views</span><b>%(views)s</b></div>
 <div class="card"><span>Downloads</span><b>%(downloads)s</b></div>
 <div class="card"><span>Unique views</span><b>%(uviews)s</b></div>
 <div class="card"><span>Unique downloads</span><b>%(udownloads)s</b></div>
</div>
<div class="scroll"><table><thead><tr>
 <th>ID</th><th>Title</th><th class="num">Views</th><th class="num">Downloads</th>
 <th class="num">Uniq views</th><th class="num">Uniq dl</th><th class="num">DL/day</th>
 <th>Downloads trend</th>
</tr></thead><tbody>
%(rows)s
</tbody></table></div>
<footer>DL/day is downloads divided by days since publication. Sparklines plot the
downloads column of every run recorded in the history CSV.</footer>
</div></body></html>
"""


def html_target_ok(path, force):
    """Refuse to clobber a file this tool did not generate, unless --force."""
    if force or not os.path.isfile(path):
        return True
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            head = fh.read(4096)
    except OSError:
        return True          # write_html will report the real problem
    return HTML_MARKER in head


def write_html(path, records, prev, prev_ts, all_rows, generated):
    series = {}
    for r in sorted(all_rows, key=lambda x: x["timestamp"]):
        series.setdefault(str(r["record_id"]), []).append(int(r["downloads"]))

    totals = {k: sum(r[k] for r in records) for k in STAT_KEYS}
    body = []
    for rec in records:
        p = prev.get(rec["record_id"])
        rate = per_day(rec["downloads"], rec["days"])
        dv = fmt_delta(rec["views"], p, "views")
        dd = fmt_delta(rec["downloads"], p, "downloads")
        url = f"{BASE}/records/{rec['record_id']}"
        age = ("" if rec["days"] is None
               else " &middot; %d days ago" % max(rec["days"], 0))
        body.append(
            "<tr>"
            '<td class="id"><a href="%s">%s</a></td>'
            '<td class="title">%s<span class="pub">published %s%s</span></td>'
            '<td class="num">%s<span class="d %s">%s</span></td>'
            '<td class="num">%s<span class="d %s">%s</span></td>'
            '<td class="num">%s</td><td class="num">%s</td><td class="num">%s</td>'
            '<td class="spark-cell">%s</td>'
            "</tr>" % (
                html.escape(url), html.escape(str(rec["record_id"])),
                html.escape(str(rec["title"] or "(untitled)")),
                html.escape(str(rec["publication_date"] or "?")), age,
                f"{rec['views']:,}", delta_cls(dv), html.escape(dv),
                f"{rec['downloads']:,}", delta_cls(dd), html.escape(dd),
                f"{rec['unique_views']:,}", f"{rec['unique_downloads']:,}",
                "?" if rate is None else "%.2f" % rate,
                sparkline(series.get(str(rec["record_id"]), [])),
            )
        )

    doc = HTML_TEMPLATE % {
        "generated": html.escape(generated),
        "base": html.escape(BASE),
        "records": len(records),
        "runs": len({r["timestamp"] for r in all_rows}),
        "views": f"{totals['views']:,}",
        "downloads": f"{totals['downloads']:,}",
        "uviews": f"{totals['unique_views']:,}",
        "udownloads": f"{totals['unique_downloads']:,}",
        "prev": html.escape(prev_ts) if prev_ts else "no previous run",
        "rows": "\n".join(body),
    }
    try:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(doc)
    except OSError as exc:
        note(f"  could not write HTML {path}: {exc}")
        return False
    return True


# ------------------------------------------------------------------------- main

def collect(session, record_ids, labels, auth=False):
    """Fetch stats for each record id. Returns the list of normalised rows."""
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    out = []
    for rid in record_ids:
        rec = fetch_record(session, rid, auth=auth)
        if not isinstance(rec, dict):
            note(f"  [{rid}] skipped -- record not readable")
            continue
        meta = rec.get("metadata") or {}
        stats = rec.get("stats") or {}
        title = meta.get("title") or rec.get("title") or labels.get(str(rid)) or ""
        pub = meta.get("publication_date") or ""
        row = {
            "timestamp": stamp,
            "record_id": str(rid),
            "title": str(title),
            "publication_date": str(pub),
            "views": as_int(stats.get("views")),
            "downloads": as_int(stats.get("downloads")),
            "unique_views": as_int(stats.get("unique_views")),
            "unique_downloads": as_int(stats.get("unique_downloads")),
        }
        row["days"] = days_since(pub)
        out.append(row)
        note(f"  [{rid}] views={row['views']:,} downloads={row['downloads']:,}"
             f"  {clip(title, 40)}")
    return out


def main():
    global JSON_MODE

    ap = argparse.ArgumentParser(
        description="Read-only metrics tracker for your published Zenodo records.",
        epilog="This tool never writes to Zenodo -- it issues GET requests only.")
    ap.add_argument("--json", action="store_true",
                    help="dump the raw collected data to stdout instead of a table")
    ap.add_argument("--csv", metavar="PATH", default=DEFAULT_CSV,
                    help="history CSV to append to (default: %(default)s)")
    ap.add_argument("--html", metavar="PATH",
                    help="also write a self-contained HTML dashboard to PATH")
    ap.add_argument("--no-history", action="store_true",
                    help="do not append this run to the history CSV")
    ap.add_argument("--record", metavar="ID", action="append", default=[],
                    help="track this public record id instead of your own "
                         "depositions (repeatable, needs no token)")
    ap.add_argument("--force", action="store_true",
                    help="allow --html to overwrite a file this tool did not write")
    args = ap.parse_args()
    JSON_MODE = args.json

    session = requests.Session()
    note(f"host    : {BASE}")

    labels = {}
    authed = False
    if args.record:
        record_ids = [str(x).strip() for x in args.record if str(x).strip()]
        if not record_ids:
            note("no usable record ids were given.")
            return 2
        note(f"records : {len(record_ids)} explicit id(s), public read only")
    else:
        if not TOKEN:
            write_line(sys.stderr,
                       "ZENODO_TOKEN is not set in this shell, so your deposition "
                       "list cannot be read.\nSet it, or pass --record ID to track "
                       "specific public records without a token.")
            return 2
        note(f"token   : {mask(TOKEN)}")
        note("GET /api/deposit/depositions")
        deps = fetch_depositions(session)
        if deps is None:
            return 1
        published = [d for d in deps if d.get("state") == "done"]
        note(f"  {len(deps)} deposition(s), {len(published)} published")
        if not published:
            note("nothing published yet -- no metrics to track.")
            return 0
        # The depositions call already proved the token is good, so record
        # reads can carry it too and use the higher authenticated rate cap.
        authed = True
        record_ids = []
        for d in published:
            rid = str(d.get("record_id") or d.get("id") or "").strip()
            if not rid:
                note("  skipping a published deposition with no id")
                continue
            record_ids.append(rid)
            labels[rid] = d.get("title") or ""

    note("GET /api/records/:id")
    records = collect(session, record_ids, labels, auth=authed)
    if not records:
        note("no readable records -- nothing to report.")
        return 1

    history = load_history(args.csv)
    prev, prev_ts = previous_snapshot(history)

    wrote = False
    if not args.no_history:
        wrote = append_history(args.csv, records)

    records.sort(key=lambda r: (r["downloads"], r["views"]), reverse=True)

    if args.json:
        json.dump({
            "base": BASE,
            "generated": records[0]["timestamp"],
            "previous_run": prev_ts,
            "history_csv": os.path.abspath(args.csv) if wrote else None,
            "records": [
                dict(r,
                     downloads_per_day=per_day(r["downloads"], r["days"]),
                     delta_views=(r["views"] - prev[r["record_id"]]["views"]
                                  if r["record_id"] in prev else None),
                     delta_downloads=(r["downloads"] - prev[r["record_id"]]["downloads"]
                                      if r["record_id"] in prev else None))
                for r in records
            ],
        }, sys.stdout, indent=2)
        sys.stdout.write("\n")
    else:
        show()
        render_table(records, prev, prev_ts)

    if wrote:
        note(f"appended {len(records)} row(s) to {os.path.abspath(args.csv)}")
    elif args.no_history:
        note("history not updated (--no-history)")

    if args.html:
        if not html_target_ok(args.html, args.force):
            note(f"refusing to overwrite {os.path.abspath(args.html)}: it was not "
                 "written by this tool.")
            note("pick another --html path, or pass --force to overwrite it.")
            return 1
        all_rows = history + records
        if write_html(args.html, records, prev, prev_ts, all_rows,
                      records[0]["timestamp"]):
            note(f"wrote dashboard {os.path.abspath(args.html)}")

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
